/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstappgraph;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Fares Abu Ali
 */
public class FirstAppStackGraphics extends javax.swing.JFrame {

    /**
     * Creates new form FirstAppStackGraphics
     */
    public FirstAppStackGraphics() {
        

       
        initComponents();
        
                pnlMainInside.setPreferredSize(new Dimension(10000, 50 * 42));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnlMainInside = new javax.swing.JPanel();
        pnlMenue = new javax.swing.JPanel();
        pnlSizeAndPeek = new javax.swing.JPanel();
        lblTopValue = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtValue = new javax.swing.JTextField();
        btnPush = new javax.swing.JButton();
        lblEnter = new javax.swing.JLabel();
        btnPop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainInside.setBackground(new java.awt.Color(204, 255, 255));
        pnlMainInside.setMaximumSize(new java.awt.Dimension(100000, 100000));
        pnlMainInside.setPreferredSize(new java.awt.Dimension(5000, 1000));
        pnlMainInside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pnlSizeAndPeek.setBackground(new java.awt.Color(255, 255, 255));
        pnlSizeAndPeek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblTopValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTopValue.setText("Peek = ");

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSize.setText("Size = ");

        javax.swing.GroupLayout pnlSizeAndPeekLayout = new javax.swing.GroupLayout(pnlSizeAndPeek);
        pnlSizeAndPeek.setLayout(pnlSizeAndPeekLayout);
        pnlSizeAndPeekLayout.setHorizontalGroup(
            pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeAndPeekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlSizeAndPeekLayout.setVerticalGroup(
            pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeAndPeekLayout.createSequentialGroup()
                .addComponent(lblTopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValueKeyTyped(evt);
            }
        });

        btnPush.setBackground(new java.awt.Color(51, 51, 51));
        btnPush.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPush.setForeground(new java.awt.Color(255, 255, 255));
        btnPush.setText("PUSH");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        lblEnter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnter.setText("Enter a value:-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPush)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPush))
                .addContainerGap())
        );

        btnPop.setBackground(new java.awt.Color(51, 51, 51));
        btnPop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPop.setForeground(new java.awt.Color(255, 255, 255));
        btnPop.setText("POP");
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenueLayout = new javax.swing.GroupLayout(pnlMenue);
        pnlMenue.setLayout(pnlMenueLayout);
        pnlMenueLayout.setHorizontalGroup(
            pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenueLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSizeAndPeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlMenueLayout.setVerticalGroup(
            pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSizeAndPeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnPop)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlMainInside.add(pnlMenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 340, 220));

        jPanel1.add(pnlMainInside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 490));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKeyTyped
      
    }//GEN-LAST:event_txtValueKeyTyped

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed

        
    }//GEN-LAST:event_btnPushActionPerformed

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed

     
    }//GEN-LAST:event_btnPopActionPerformed

       @Override
    public void paint(Graphics gr) {

        super.paint(gr);

        gr.setFont(new Font("Tahoma", 1, 14));

        gr.drawRect(20, 50, 50, 50); // x,y,width,height
        gr.drawRect(20, 50+50, 50, 50); // x,y,width,height

        gr.drawString("25", 20 + 15, 50 + 30); // String , x ,y

        gr.fillRect(WIDTH, WIDTH, WIDTH, HEIGHT);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstAppStackGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstAppStackGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstAppStackGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstAppStackGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstAppStackGraphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTopValue;
    private javax.swing.JPanel pnlMainInside;
    private javax.swing.JPanel pnlMenue;
    private javax.swing.JPanel pnlSizeAndPeek;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
