/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstappgraph;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Fares Abu Ali
 */
public class LinkedListGraphScroll extends javax.swing.JFrame {

    int x_CorRect;
    int y_CorRect;
    int widthForRect;
    int heightForRect;
    int arrowLength;
    int largestNumOfDigits;

    MySinglyLinkedList<Object> msl;

    public LinkedListGraphScroll() {
        initComponents();

        x_CorRect = 20;
        y_CorRect = 60;
        widthForRect = 30;
        heightForRect = 50;
        arrowLength = 50;
        largestNumOfDigits = 1;

        msl = new MySinglyLinkedList<>();

        System.out.println(getWidth());
    }

    public void resetAllCoordinates() {
        x_CorRect = 20;
        y_CorRect = 60;

    }

    public void setLargesNumberOfDigits(String str) {

        if (str.length() > largestNumOfDigits) {
            int difference = str.length() - largestNumOfDigits;
            largestNumOfDigits = str.length();
            widthForRect += 14 * difference;
        }

    }

    @Override
    public void paint(Graphics gr) {

        resetAllCoordinates();
        super.paint(gr);

        for (int i = 0; i < msl.size(); i++) {

            gr.setFont(new Font("Times New Roman", 1, 20));

            if (x_CorRect > this.getWidth() - widthForRect) {
                x_CorRect = 20;
                y_CorRect += heightForRect + 10;
            }
            //the first rectangle for the element
            gr.drawRect(x_CorRect, y_CorRect, widthForRect, heightForRect);// x , y ,width,height    

            //the second rectangle for the (Node next)
            gr.drawRect((int) (x_CorRect + (3 / 4.0) * widthForRect), y_CorRect, widthForRect / 4, heightForRect);// x , y ,width,height    
            gr.drawString(msl.get(i).toString(), x_CorRect + 5, y_CorRect + (int) (0.5 * heightForRect));
            gr.setColor(new Color(0, 114, 187));// RGB
            gr.fillRect((int) (x_CorRect + (3 / 4.0) * widthForRect), y_CorRect, widthForRect / 4, heightForRect);

            //----------------------------------------------------
            gr.setColor(Color.black);

            //draw the body of the arrow
            gr.drawLine(x_CorRect + widthForRect, (int) (y_CorRect + (1 / 2.0) * heightForRect), x_CorRect + widthForRect + arrowLength, (int) (y_CorRect + (1 / 2.0) * heightForRect));  // x1,y1,x2,y2

            // draw the upper inclined part
            gr.drawLine((int) (x_CorRect + widthForRect + (3 / 5.0) * arrowLength), (int) (y_CorRect + 0.3 * heightForRect), x_CorRect + widthForRect + arrowLength, (int) (y_CorRect + (1 / 2.0) * heightForRect));  // x1,y1,x2,y2

            // draw the lowe inclined part
            gr.drawLine((int) (x_CorRect + widthForRect + (3 / 5.0) * arrowLength), (int) (y_CorRect + 0.7 * heightForRect), x_CorRect + widthForRect + arrowLength, (int) (y_CorRect + (1 / 2.0) * heightForRect));  // x1,y1,x2,y2

            x_CorRect += (widthForRect + arrowLength);

        }

        gr.setFont(new Font("Thoma", 0, 18));

        gr.drawString("null", x_CorRect + 5, y_CorRect + (int) (0.5 * heightForRect) + 5);

        System.out.println(msl);

        lblSize.setText("Size = " + msl.size());

        //gr.drawLine(20 + 80 - 15, 60 + 25 - 15, 20+80+50 ,60 + 25);  // x1,y1,x2,y2
        //gr.drawLine(210, 215, 220, 205);
        // gr.clearRect(100, 170, 80, 70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenue = new javax.swing.JPanel();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblIndex = new javax.swing.JLabel();
        txtIndex = new javax.swing.JTextField();
        btnAddFirst = new javax.swing.JButton();
        btnAddLast = new javax.swing.JButton();
        btnAddByIndex = new javax.swing.JButton();
        btnRemoveFirst = new javax.swing.JButton();
        btnRemoveLast = new javax.swing.JButton();
        btnRemoveByIndex = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSet = new javax.swing.JButton();
        btnSet1 = new javax.swing.JButton();
        lblInfo3 = new javax.swing.JLabel();
        cmboDataType = new javax.swing.JComboBox<>();
        lblSize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEnterArray = new javax.swing.JTextField();
        btnAddArray = new javax.swing.JButton();
        btnRemoveArray = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        pnlMenue.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        lblValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValue.setText("Enter a value:");

        txtValue.setBackground(new java.awt.Color(204, 204, 204));
        txtValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValueActionPerformed(evt);
            }
        });
        txtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValueKeyTyped(evt);
            }
        });

        lblIndex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIndex.setText("Enter an Index:");

        txtIndex.setBackground(new java.awt.Color(204, 204, 204));
        txtIndex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIndex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIndexKeyTyped(evt);
            }
        });

        btnAddFirst.setBackground(new java.awt.Color(214, 24, 132));
        btnAddFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFirst.setText("AddFirst");
        btnAddFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFirstActionPerformed(evt);
            }
        });

        btnAddLast.setBackground(new java.awt.Color(214, 24, 132));
        btnAddLast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddLast.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLast.setText("Add Last");
        btnAddLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLastActionPerformed(evt);
            }
        });

        btnAddByIndex.setBackground(new java.awt.Color(214, 24, 132));
        btnAddByIndex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddByIndex.setForeground(new java.awt.Color(255, 255, 255));
        btnAddByIndex.setText("Add by Index");
        btnAddByIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddByIndexActionPerformed(evt);
            }
        });

        btnRemoveFirst.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveFirst.setText("Remove First");
        btnRemoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFirstActionPerformed(evt);
            }
        });

        btnRemoveLast.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveLast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveLast.setText("Remove Last");
        btnRemoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLastActionPerformed(evt);
            }
        });

        btnRemoveByIndex.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveByIndex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveByIndex.setText("Remove by Index");
        btnRemoveByIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveByIndexActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSet.setBackground(new java.awt.Color(141, 182, 0));
        btnSet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSet.setText("Set(index,value)");
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        btnSet1.setBackground(new java.awt.Color(141, 182, 0));
        btnSet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSet1.setText("get(index)");
        btnSet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSet1ActionPerformed(evt);
            }
        });

        lblInfo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfo3.setText("Choose Data Type:");
        lblInfo3.setToolTipText("");

        cmboDataType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmboDataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Character", "String", "Double/Float" }));
        cmboDataType.setSelectedIndex(-1);
        cmboDataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboDataTypeActionPerformed(evt);
            }
        });

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSize.setText("Size= ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Enter array of values");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        txtEnterArray.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtEnterArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, 30));

        btnAddArray.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddArray.setText("add");
        btnAddArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArrayActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 70, 50));

        btnRemoveArray.setBackground(new java.awt.Color(255, 255, 255));
        btnRemoveArray.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoveArray.setText("remove");
        btnRemoveArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveArrayActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 70, 50));

        javax.swing.GroupLayout pnlMenueLayout = new javax.swing.GroupLayout(pnlMenue);
        pnlMenue.setLayout(pnlMenueLayout);
        pnlMenueLayout.setHorizontalGroup(
            pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenueLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMenueLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(cmboDataType, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addComponent(btnAddFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnAddLast, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnAddByIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnRemoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnRemoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnRemoveByIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSet1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlMenueLayout.setVerticalGroup(
            pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenueLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addComponent(lblValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addComponent(lblInfo3)
                        .addGap(23, 23, 23)
                        .addComponent(lblSize))
                    .addComponent(cmboDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddLast, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddByIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveLast, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveByIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSet1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlMenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(pnlMenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKeyTyped

        char c = evt.getKeyChar();

        if (cmboDataType.getSelectedIndex() == 0) {// integer

            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {

                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "You are allowed to enter digit only!");

            }

        } else if (cmboDataType.getSelectedIndex() == 1) {// char

            String value = txtValue.getText();

            if (value.length() > 0) {

                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "You are allowed to enter Characters (1 Byte) only!");
            }

        } else if (cmboDataType.getSelectedIndex() == 3) {//Double/Float

            if (c != '.' && !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {

                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "You are allowed to enter digits or decimal points only!");
            }

        }
    }//GEN-LAST:event_txtValueKeyTyped

    private void txtIndexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIndexKeyTyped

        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "You are allowed to enter digit only!");

        }
    }//GEN-LAST:event_txtIndexKeyTyped

    private void btnAddFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFirstActionPerformed

        String value = txtValue.getText();

        if (value.length() > 0) {

            msl.addFirst(value);
            //System.out.println(al);

            setLargesNumberOfDigits(value);

            repaint();

        } else {

            JOptionPane.showMessageDialog(rootPane, "Please enter the value which will be added in the first");
        }

        System.out.println(msl);
        // txtArea.append(al.toString());

        setLargesNumberOfDigits(value);
    }//GEN-LAST:event_btnAddFirstActionPerformed

    private void btnAddLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLastActionPerformed

        String value = txtValue.getText();

        if (value.length() > 0) {

            msl.addLast(value);
            //System.out.println(al);

            setLargesNumberOfDigits(value);

            repaint();

        } else {

            JOptionPane.showMessageDialog(rootPane, "Please enter the value which will be added");
        }

        // txtArea.append(al.toString());
        System.out.println(msl);

    }//GEN-LAST:event_btnAddLastActionPerformed

    private void btnAddByIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddByIndexActionPerformed

        String value = txtValue.getText();

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the value which will be added");
        }

        String indexStr = txtIndex.getText();
        if (indexStr.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the index");
        } else {

            int index = 0;

            boolean isValidIndex = true;

            try {
                index = Integer.parseInt(indexStr);

                msl.add(index, value);

            } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {

                // isValidIndex=false;
                if (ex instanceof NumberFormatException) {
                    JOptionPane.showMessageDialog(rootPane, "Please enter a valid index, a positive integer only");
                }

                if (ex instanceof ArrayIndexOutOfBoundsException) {
                    JOptionPane.showMessageDialog(rootPane, "Index= " + index + ", size= " + msl.size()
                            + ". Index cannot be bigger than the size");
                }

            }

            // System.out.println(al);
            //txtArea.append(al.toString());
            setLargesNumberOfDigits(value);

            repaint();

            System.out.println(msl);

            setLargesNumberOfDigits(value);

        }
    }//GEN-LAST:event_btnAddByIndexActionPerformed

    private void btnRemoveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFirstActionPerformed

        if (msl.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Empty List");

        } else {
            msl.removeFirst();

            // System.out.println(al);
            repaint();

            System.out.println(msl);
        }
    }//GEN-LAST:event_btnRemoveFirstActionPerformed

    private void btnRemoveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLastActionPerformed

        if (msl.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Empty List");

        } else {
            msl.removeLast();
            repaint();

            System.out.println(msl);
        }
    }//GEN-LAST:event_btnRemoveLastActionPerformed

    private void btnRemoveByIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveByIndexActionPerformed

        if (msl.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Empty List");

        } else {

            String indexStr = txtIndex.getText();

            if (indexStr.length() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please enter the index");
            } else {

                int index = 0;

                try {
                    index = Integer.parseInt(indexStr);

                    msl.remove(index);
                } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {

                    if (ex instanceof NumberFormatException) {
                        JOptionPane.showMessageDialog(rootPane, "Please enter a valid index, a positive integer only");
                    }

                    if (ex instanceof ArrayIndexOutOfBoundsException) {
                        JOptionPane.showMessageDialog(rootPane, "Index= " + index + ", size= " + msl.size()
                                + ". Index must be less than the size");
                    }

                }

                repaint();

                System.out.println(msl);

            }
        }
    }//GEN-LAST:event_btnRemoveByIndexActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String value = txtValue.getText();

        int loc = -1;

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the value you want to search for");
        } else {

            loc = msl.indexOf(value);

            if (loc == -1) {
                JOptionPane.showMessageDialog(rootPane, "The value " + value + " was not found in the list");

            } else {
                JOptionPane.showMessageDialog(rootPane, "The value " + value + " is at index " + loc + " in the list");

            }

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        msl.clear();
        repaint();

        //clearLabelsTexts();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed

        String value = txtValue.getText();

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the value which will be added");
        }

        String indexStr = txtIndex.getText();
        if (indexStr.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the index");
        } else {

            int index = 0;

            boolean isValidIndex = true;

            try {
                index = Integer.parseInt(indexStr);

                msl.set(index, value);

            } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {

                // isValidIndex=false;
                if (ex instanceof NumberFormatException) {
                    JOptionPane.showMessageDialog(rootPane, "Please enter a valid index, a positive integer only");
                }

                if (ex instanceof ArrayIndexOutOfBoundsException) {
                    JOptionPane.showMessageDialog(rootPane, "Index= " + index + ", size= " + msl.size()
                            + ". Index cannot be bigger than the size");
                }

            }

            // System.out.println(al);
            //txtArea.append(al.toString());
            repaint();

            System.out.println(msl);

        }
    }//GEN-LAST:event_btnSetActionPerformed

    private void btnSet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSet1ActionPerformed

        String indexStr = txtIndex.getText();
        if (indexStr.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please enter the index");
        } else {

            int index = 0;

            boolean isValidIndex = true;

            try {
                index = Integer.parseInt(indexStr);

                JOptionPane.showMessageDialog(rootPane, "the value at index " + index + " is: " + msl.get(index));

            } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {

                // isValidIndex=false;
                if (ex instanceof NumberFormatException) {
                    JOptionPane.showMessageDialog(rootPane, "Please enter a valid index, a positive integer only");
                }

                if (ex instanceof ArrayIndexOutOfBoundsException) {
                    JOptionPane.showMessageDialog(rootPane, "Index= " + index + ", size= " + msl.size()
                            + ". Index cannot be bigger than the size");
                }

            }

            // System.out.println(al);
            //txtArea.append(al.toString());
            repaint();

            System.out.println(msl);

        }
    }//GEN-LAST:event_btnSet1ActionPerformed

    private void cmboDataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboDataTypeActionPerformed

        System.out.println(cmboDataType.getSelectedIndex());
    }//GEN-LAST:event_cmboDataTypeActionPerformed

    private void btnAddArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArrayActionPerformed

        String values = txtEnterArray.getText();
        String[] ar = values.split(",");

        for (int i = 0; i < ar.length; i++) {
            setLargesNumberOfDigits(ar[i]);

            msl.addLast(ar[i]);
        }

        repaint();
    }//GEN-LAST:event_btnAddArrayActionPerformed

    private void btnRemoveArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveArrayActionPerformed

        String values = txtEnterArray.getText();
        String[] ar = values.split(",");

        for (int i = 0; i < ar.length; i++) {
            setLargesNumberOfDigits(ar[i]);

            msl.removeAllOccurences(ar[i]);
        }

        repaint();
    }//GEN-LAST:event_btnRemoveArrayActionPerformed

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinkedListGraphScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinkedListGraphScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinkedListGraphScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinkedListGraphScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinkedListGraphScroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArray;
    private javax.swing.JButton btnAddByIndex;
    private javax.swing.JButton btnAddFirst;
    private javax.swing.JButton btnAddLast;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemoveArray;
    private javax.swing.JButton btnRemoveByIndex;
    private javax.swing.JButton btnRemoveFirst;
    private javax.swing.JButton btnRemoveLast;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSet;
    private javax.swing.JButton btnSet1;
    private javax.swing.JComboBox<String> cmboDataType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblValue;
    private javax.swing.JPanel pnlMenue;
    private javax.swing.JTextField txtEnterArray;
    private javax.swing.JTextField txtIndex;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
