package VisualRepresent;


import ArrayList_based.MyStackAL;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fares Abu Ali
 */
public class StackScroll extends javax.swing.JFrame {

    int arrayOfLabelsSize;
    JLabel[] lbls;
    JLabel lblPeek;
    int initial_Y = 2000;
    int peekPointerLocation = initial_Y + 10;

    MyStackAL<Object> ms;

    public StackScroll() {

        ms = new MyStackAL<>();

        initComponents();

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocation(300, 100);
        setTitle("Fares H.Abu Ali- MyStackClass Visualization");
        setResizable(false);
        pnlMainInside.setPreferredSize(new Dimension(1000, 600));

        lblPeek = new JLabel("Peek-->");
        
        pnlMenue.setVisible(false);
        
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        //createStackShape();
    }

    public void createStackShape() {

        lblPeek = new JLabel("Peek-->");
        lblPeek.setFont(new Font("Thoma", 1, 14));

        pnlMainInside.add(lblPeek, new AbsoluteConstraints(420, 370, 59, 20));// x,y,width,height

        lblPeek.setVisible(false);

        for (int i = 0; i < arrayOfLabelsSize; i++) {
            lbls[i] = new JLabel();
            pnlMainInside.add(lbls[i], new AbsoluteConstraints(470, initial_Y, 59, 40));// x,y,width,height

             lbls[i].setFont(new Font("Tahoma", 1, 14));
            lbls[i].setHorizontalAlignment(SwingConstants.CENTER);
            //lbls[i].setText(i + "");
            lbls[i].setVisible(false);
            lbls[i].setBorder(new LineBorder(Color.black, 1));
            initial_Y -= 40;
        }

        //reset 
        initial_Y = 2000;
    }

    public void clearStack() {

        lblPeek.setVisible(false);
        lblTopValue.setText("");
        lblSize.setText("");
        txtValue.setText("");

        if (lbls != null) {
            for (int i = 0; i < arrayOfLabelsSize; i++) {
                lbls[i].setVisible(false);
            }
        }

        ms.clear();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlScroll = new javax.swing.JScrollPane();
        pnlMainInside = new javax.swing.JPanel();
        cmboDataType = new javax.swing.JComboBox<>();
        lblInfo1 = new javax.swing.JLabel();
        rdbtn1 = new javax.swing.JRadioButton();
        rdbtn2 = new javax.swing.JRadioButton();
        rdbtn3 = new javax.swing.JRadioButton();
        rdbtn4 = new javax.swing.JRadioButton();
        rdbtn5 = new javax.swing.JRadioButton();
        lblInfo2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        pnlMenue = new javax.swing.JPanel();
        pnlSizeAndPeek = new javax.swing.JPanel();
        lblTopValue = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtValue = new javax.swing.JTextField();
        btnPush = new javax.swing.JButton();
        lblEnter = new javax.swing.JLabel();
        btnPop = new javax.swing.JButton();
        btnMainMenu1 = new javax.swing.JButton();
        btnMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlScroll.setBackground(new java.awt.Color(255, 255, 255));
        pnlScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlScroll.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlScroll.setAutoscrolls(true);
        pnlScroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlScroll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlScroll.setMaximumSize(new java.awt.Dimension(100000, 100000));
        pnlScroll.setName(""); // NOI18N
        pnlScroll.setPreferredSize(new java.awt.Dimension(1000, 100));

        pnlMainInside.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainInside.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlMainInside.setMaximumSize(new java.awt.Dimension(100000, 100000));
        pnlMainInside.setPreferredSize(new java.awt.Dimension(5000, 1000));

        cmboDataType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmboDataType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Integer", "Character", "String", "Double/Float" }));
        cmboDataType.setSelectedIndex(-1);
        cmboDataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboDataTypeActionPerformed(evt);
            }
        });

        lblInfo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfo1.setText("Choose Approximate Size of Queue:");
        lblInfo1.setToolTipText("");

        rdbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtn1.setText("10");
        rdbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn1ActionPerformed(evt);
            }
        });

        rdbtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtn2.setText("50");
        rdbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn2ActionPerformed(evt);
            }
        });

        rdbtn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtn3.setText("100");
        rdbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn3ActionPerformed(evt);
            }
        });

        rdbtn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtn4.setText("500");
        rdbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn4ActionPerformed(evt);
            }
        });

        rdbtn5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbtn5.setText("1000");
        rdbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn5ActionPerformed(evt);
            }
        });

        lblInfo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfo2.setText("Choose Data Type:");
        lblInfo2.setToolTipText("");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Stack Visualization");

        pnlMenue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        pnlSizeAndPeek.setBackground(new java.awt.Color(255, 255, 255));
        pnlSizeAndPeek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblTopValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTopValue.setText("Peek = ");

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSize.setText("Size = ");

        javax.swing.GroupLayout pnlSizeAndPeekLayout = new javax.swing.GroupLayout(pnlSizeAndPeek);
        pnlSizeAndPeek.setLayout(pnlSizeAndPeekLayout);
        pnlSizeAndPeekLayout.setHorizontalGroup(
            pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeAndPeekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlSizeAndPeekLayout.setVerticalGroup(
            pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeAndPeekLayout.createSequentialGroup()
                .addComponent(lblTopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValueKeyTyped(evt);
            }
        });

        btnPush.setBackground(new java.awt.Color(51, 51, 51));
        btnPush.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPush.setForeground(new java.awt.Color(255, 255, 255));
        btnPush.setText("PUSH");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        lblEnter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnter.setText("Enter a value:-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPush)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPush))
                .addContainerGap())
        );

        btnPop.setBackground(new java.awt.Color(51, 51, 51));
        btnPop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPop.setForeground(new java.awt.Color(255, 255, 255));
        btnPop.setText("POP");
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenueLayout = new javax.swing.GroupLayout(pnlMenue);
        pnlMenue.setLayout(pnlMenueLayout);
        pnlMenueLayout.setHorizontalGroup(
            pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSizeAndPeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnPop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlMenueLayout.setVerticalGroup(
            pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSizeAndPeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnlMenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenueLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnPop)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnMainMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMainMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitAccount.png"))); // NOI18N
        btnMainMenu1.setBorder(null);
        btnMainMenu1.setContentAreaFilled(false);
        btnMainMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMainMenu1MouseReleased(evt);
            }
        });
        btnMainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainInsideLayout = new javax.swing.GroupLayout(pnlMainInside);
        pnlMainInside.setLayout(pnlMainInsideLayout);
        pnlMainInsideLayout.setHorizontalGroup(
            pnlMainInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInsideLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlMainInsideLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlMainInsideLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cmboDataType, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(rdbtn1)
                .addGap(13, 13, 13)
                .addComponent(rdbtn2)
                .addGap(13, 13, 13)
                .addComponent(rdbtn3))
            .addGroup(pnlMainInsideLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(rdbtn4)
                .addGap(16, 16, 16)
                .addComponent(rdbtn5))
            .addGroup(pnlMainInsideLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlMenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlMainInsideLayout.setVerticalGroup(
            pnlMainInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainInsideLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(pnlMainInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfo2)
                    .addComponent(lblInfo1))
                .addGap(3, 3, 3)
                .addGroup(pnlMainInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmboDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtn1)
                    .addComponent(rdbtn2)
                    .addComponent(rdbtn3))
                .addGap(3, 3, 3)
                .addGroup(pnlMainInsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtn4)
                    .addComponent(rdbtn5))
                .addGap(10, 10, 10)
                .addComponent(pnlMenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlScroll.setViewportView(pnlMainInside);

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMainMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitAccount.png"))); // NOI18N
        btnMainMenu.setBorder(null);
        btnMainMenu.setContentAreaFilled(false);
        btnMainMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMainMenuMouseReleased(evt);
            }
        });
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmboDataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboDataTypeActionPerformed

        txtValue.setText("");


    }//GEN-LAST:event_cmboDataTypeActionPerformed

    private void rdbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn1ActionPerformed
        pnlMenue.setVisible(true);

        clearStack();

        ms = new MyStackAL<>();

        rdbtn2.setSelected(false);
        rdbtn3.setSelected(false);
        rdbtn4.setSelected(false);
        rdbtn5.setSelected(false);

        arrayOfLabelsSize = Integer.parseInt(rdbtn1.getText());
        lbls = new JLabel[arrayOfLabelsSize];
        initial_Y = arrayOfLabelsSize * 40;

        pnlMainInside.setPreferredSize(new Dimension(1000, arrayOfLabelsSize * 70));
        
   pnlMainInside.remove(pnlMenue);
        pnlMainInside.add(pnlMenue, new AbsoluteConstraints(10, 230, 340, 220));// x,y,width,height
        pnlMenue.setVisible(true);
        createStackShape();
    }//GEN-LAST:event_rdbtn1ActionPerformed

    private void rdbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn2ActionPerformed

        pnlMenue.setVisible(true);
        clearStack();

        ms = new MyStackAL<>();

        rdbtn1.setSelected(false);
        rdbtn3.setSelected(false);
        rdbtn4.setSelected(false);
        rdbtn5.setSelected(false);

        arrayOfLabelsSize = Integer.parseInt(rdbtn2.getText());
        initial_Y = arrayOfLabelsSize * 40;

        lbls = new JLabel[arrayOfLabelsSize];

        pnlMainInside.setPreferredSize(new Dimension(1000, arrayOfLabelsSize * 42));

        pnlMainInside.remove(pnlMenue);
        pnlMainInside.add(pnlMenue, new AbsoluteConstraints(10, arrayOfLabelsSize * 37, 340, 220));// x,y,width,height
        pnlMenue.setVisible(true);

        createStackShape();


    }//GEN-LAST:event_rdbtn2ActionPerformed

    private void rdbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn3ActionPerformed
        pnlMenue.setVisible(true);

        clearStack();
        ms = new MyStackAL<>();

        rdbtn1.setSelected(false);
        rdbtn2.setSelected(false);
        rdbtn4.setSelected(false);
        rdbtn5.setSelected(false);

        arrayOfLabelsSize = Integer.parseInt(rdbtn3.getText());
        lbls = new JLabel[arrayOfLabelsSize];
        initial_Y = arrayOfLabelsSize * 40;

        pnlMainInside.setPreferredSize(new Dimension(1000, arrayOfLabelsSize * 41));

        pnlMainInside.remove(pnlMenue);
        pnlMainInside.add(pnlMenue, new AbsoluteConstraints(10, arrayOfLabelsSize * 38, 340, 220));// x,y,width,height
        pnlMenue.setVisible(true);

        createStackShape();
    }//GEN-LAST:event_rdbtn3ActionPerformed

    private void rdbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn4ActionPerformed

        pnlMenue.setVisible(true);

        clearStack();

        ms = new MyStackAL<>();

        rdbtn1.setSelected(false);
        rdbtn2.setSelected(false);
        rdbtn3.setSelected(false);
        rdbtn5.setSelected(false);

        arrayOfLabelsSize = Integer.parseInt(rdbtn4.getText());
        lbls = new JLabel[arrayOfLabelsSize];
        initial_Y = arrayOfLabelsSize * 40;

        pnlMainInside.setPreferredSize(new Dimension(1000, arrayOfLabelsSize * 40 + 100));
        
          pnlMainInside.remove(pnlMenue);
        pnlMainInside.add(pnlMenue, new AbsoluteConstraints(10,arrayOfLabelsSize * 39 + 300 , 340, 220));// x,y,width,height
        pnlMenue.setVisible(true);

        createStackShape();
    }//GEN-LAST:event_rdbtn4ActionPerformed

    private void rdbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn5ActionPerformed

        pnlMenue.setVisible(true);

        clearStack();

        ms = new MyStackAL<>();

        rdbtn1.setSelected(false);
        rdbtn2.setSelected(false);
        rdbtn3.setSelected(false);
        rdbtn4.setSelected(false);

        arrayOfLabelsSize = Integer.parseInt(rdbtn5.getText());
        lbls = new JLabel[arrayOfLabelsSize];
        initial_Y = arrayOfLabelsSize * 40;

        pnlMainInside.setPreferredSize(new Dimension(1000, arrayOfLabelsSize * 40 + 100));
        
        
          pnlMainInside.remove(pnlMenue);
        pnlMainInside.add(pnlMenue, new AbsoluteConstraints(10,arrayOfLabelsSize * 39 + 800 , 340, 220));// x,y,width,height
        pnlMenue.setVisible(true);

        createStackShape();
    }//GEN-LAST:event_rdbtn5ActionPerformed

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed

        String value = txtValue.getText();

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter a value to push");
        } else if (ms.getSize() >= arrayOfLabelsSize) {
            JOptionPane.showMessageDialog(rootPane, "Stack is Full!!!");

        } else {

            if (ms.getSize() != 0) {
                peekPointerLocation -= 40;
            }

           // System.out.println("Size=" + ms.getSize() + ", peekPointerLoc=" + peekPointerLocation);

            lbls[ms.getSize()].setText(value);
            lbls[ms.getSize()].setVisible(true);
            pnlMainInside.add(lblPeek, new AbsoluteConstraints(520, peekPointerLocation, 59, 20));//// x,y,width,height
            lblPeek.setVisible(true);

            ms.push(value);

            lblTopValue.setText("Peek = " + ms.getPeek());
            lblSize.setText("Size = " + ms.getSize());

        }
    }//GEN-LAST:event_btnPushActionPerformed

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed

        ms.pop();

        if (ms.getSize() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Stack is Empty!!");
            lbls[0].setText("");
            lbls[0].setVisible(false);
            lblTopValue.setText("Peek = null");
            lblSize.setText("Size = 0");
            lblPeek.setVisible(false);
        } else {
            lbls[ms.getSize()].setText("");
            lbls[ms.getSize()].setVisible(false);

            pnlMainInside.remove(lblPeek);

            peekPointerLocation += 40;

            pnlMainInside.add(lblPeek, new AbsoluteConstraints(420, peekPointerLocation + 1, 59, 20));
            lblPeek.setVisible(true);

            lblTopValue.setText("Peek = " + ms.getPeek());
            lblSize.setText("Size = " + ms.getSize());
        }
    }//GEN-LAST:event_btnPopActionPerformed

    private void txtValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKeyTyped
        char c = evt.getKeyChar();

        if (cmboDataType.getSelectedIndex() == 0) {// integer

            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {

                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "You are allowed to enter digit only!");

            }

        } else if (cmboDataType.getSelectedIndex() == 1) {// char

            String value = txtValue.getText();

            if (value.length() > 0) {

                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "You are allowed to enter Characters (1 Byte) only!");
            }

        } else if (cmboDataType.getSelectedIndex() == 3) {//Double/Float

            if (c != '.' && !(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                    || (c == KeyEvent.VK_DELETE))) {

                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "You are allowed to enter digits or decimal points only!");
            }

        }
    }//GEN-LAST:event_txtValueKeyTyped

    private void btnMainMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenuMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMainMenuMouseReleased

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed

        MainFrame obj = new MainFrame();
        obj.setVisible(rootPaneCheckingEnabled);

        dispose();
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnMainMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMainMenu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMainMenu1MouseReleased

    private void btnMainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenu1ActionPerformed

        MainFrame obj = new MainFrame();
        obj.setVisible(rootPaneCheckingEnabled);

        dispose();
    }//GEN-LAST:event_btnMainMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackScroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnMainMenu1;
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JComboBox<String> cmboDataType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTopValue;
    private javax.swing.JPanel pnlMainInside;
    private javax.swing.JPanel pnlMenue;
    private javax.swing.JScrollPane pnlScroll;
    private javax.swing.JPanel pnlSizeAndPeek;
    private javax.swing.JRadioButton rdbtn1;
    private javax.swing.JRadioButton rdbtn2;
    private javax.swing.JRadioButton rdbtn3;
    private javax.swing.JRadioButton rdbtn4;
    private javax.swing.JRadioButton rdbtn5;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
