
import ArrayList_based.MyArrayList;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.FocusAdapter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fares Abu Ali
 */
public class ArrayListDemo extends javax.swing.JFrame {

    MyArrayList<Object> al;
    JLabel[] lbls;

    /**
     * Creates new form ArrayListDemo
     */
    public ArrayListDemo() {

        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Fares H.Abu Ali");

        al = new MyArrayList<>();
        lbls = new JLabel[24];

        initComponents();

        createArrayListShape();
       // jScrollPane1.setLayout(new FlowLayout());
        
    }

    public void createArrayListShape() {

        int X_Cordinate = 40;
        int Y_Cordinate = 50;

        for (int i = 0; i < 24; i++) {

            if (i == 12) {
                X_Cordinate = 40;
                Y_Cordinate = 90;

            }

            lbls[i] = new JLabel();
            pnlMain.add(lbls[i], new AbsoluteConstraints(X_Cordinate, Y_Cordinate, 59, 40));// x,y,width,height
            lbls[i].setHorizontalAlignment(0);
            lbls[i].setVisible(false);
            lbls[i].setBorder(new LineBorder(Color.black, 1));

            X_Cordinate += 60;

        }

        lbls[0].setVisible(true);
        lbls[1].setVisible(true);
        lbls[2].setVisible(true);

    }

    public void clearLabelsTexts() {

        for (int i = 0; i < 24; i++) {
            lbls[i].setText("");
        }
    }

    public void fillLabels() {

        if (al.getSize() == 4 || al.getSize() == 7 || al.getSize() == 13) {

            for (int i = al.getSize() - 1; (i < al.getCapacity() && i < 24); i++) {
                lbls[i].setVisible(true);

            }

        }

        clearLabelsTexts();
        for (int i = 0; (i < al.getSize() && i < 24); i++) {
            lbls[i].setFont(new Font("Tahoma", 1, 14));
            lbls[i].setHorizontalAlignment(SwingConstants.CENTER);
            lbls[i].setText(al.get(i) + "");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        pnlMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblValue = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        lblIndex = new javax.swing.JLabel();
        txtIndex = new javax.swing.JTextField();
        btnAddFirst = new javax.swing.JButton();
        btnAddLast = new javax.swing.JButton();
        btnAddByIndex = new javax.swing.JButton();
        btnRemoveFirst = new javax.swing.JButton();
        btnRemoveLast = new javax.swing.JButton();
        btnRemoveByIndex = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ArrayList Demo");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlMain.setMaximumSize(new java.awt.Dimension(800, 400));
        pnlMain.setMinimumSize(new java.awt.Dimension(800, 400));
        pnlMain.setName(""); // NOI18N
        pnlMain.setPreferredSize(new java.awt.Dimension(800, 400));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblValue.setText("Enter a value:");
        jPanel2.add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        txtValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        lblIndex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIndex.setText("Enter an Index:");
        jPanel2.add(lblIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 30));

        txtIndex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 30));

        btnAddFirst.setBackground(new java.awt.Color(255, 51, 51));
        btnAddFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnAddFirst.setText("AddFirst");
        btnAddFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFirstActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 108, 40));

        btnAddLast.setBackground(new java.awt.Color(255, 51, 51));
        btnAddLast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddLast.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLast.setText("Add Last");
        btnAddLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLastActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 40));

        btnAddByIndex.setBackground(new java.awt.Color(255, 51, 51));
        btnAddByIndex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddByIndex.setForeground(new java.awt.Color(255, 255, 255));
        btnAddByIndex.setText("Add by Index");
        btnAddByIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddByIndexActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddByIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 140, 40));

        btnRemoveFirst.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveFirst.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveFirst.setText("Remove First");
        btnRemoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveFirstActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemoveFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 40));

        btnRemoveLast.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveLast.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveLast.setText("Remove Last");
        btnRemoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveLastActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemoveLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 110, 40));

        btnRemoveByIndex.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveByIndex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRemoveByIndex.setText("Remove by Index");
        btnRemoveByIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveByIndexActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemoveByIndex, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 140, 40));

        btnSearch.setBackground(new java.awt.Color(0, 204, 153));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 80, 40));

        btnClear.setBackground(new java.awt.Color(0, 204, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 80, 40));

        pnlMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 180));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Visualization of The ArrayList Class");
        pnlMain.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, -1));

        lblInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInfo.setText("ArrayList is empty. Size=0 and Capacity is 3");
        pnlMain.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 440, -1));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLastActionPerformed

        String value = txtValue.getText();

        if (value.length() > 0) {

            al.add(value);
            System.out.println(al);
            fillLabels();

        } else {

            JOptionPane.showMessageDialog(pnlMain, "Please enter the value which will be added");
        }

        // txtArea.append(al.toString());
        lblInfo.setText("Array List is not empty  Size = " + al.getSize() + " and Capacity is " + al.getCapacity());

    }//GEN-LAST:event_btnAddLastActionPerformed

    private void btnAddFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFirstActionPerformed

        String value = txtValue.getText();

        if (value.length() > 0) {

            al.addFirst(value);
            System.out.println(al);

            fillLabels();

        } else {

            JOptionPane.showMessageDialog(pnlMain, "Please enter the value which will be added in the first");
        }

        System.out.println(al);

        lblInfo.setText("Array List is not empty  Size = " + al.getSize() + " and Capacity is " + al.getCapacity());

        // txtArea.append(al.toString());
    }//GEN-LAST:event_btnAddFirstActionPerformed

    private void btnAddByIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddByIndexActionPerformed

        String value = txtValue.getText();

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(pnlMain, "Please enter the value which will be added");
        }

        String indexStr = txtIndex.getText();
        if (indexStr.length() == 0) {
            JOptionPane.showMessageDialog(pnlMain, "Please enter the index");
        } else {

            int index = 0;

            boolean isValidIndex = true;

            try {
                index = Integer.parseInt(indexStr);

                al.add(index, value);

            } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {

                // isValidIndex=false;
                if (ex instanceof NumberFormatException) {
                    JOptionPane.showMessageDialog(pnlMain, "Please enter a valid index, a positive integer only");
                }

                if (ex instanceof ArrayIndexOutOfBoundsException) {
                    JOptionPane.showMessageDialog(pnlMain, "Index= " + index + ", size= " + al.getSize()
                            + ". Index cannot be bigger than the size");
                }

            }

            System.out.println(al);
            //txtArea.append(al.toString());

            fillLabels();
            lblInfo.setText("Array List is not empty  Size = " + al.getSize() + " and Capacity is " + al.getCapacity());

        }


    }//GEN-LAST:event_btnAddByIndexActionPerformed

    private void btnRemoveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveFirstActionPerformed

        al.removeFirst();

        System.out.println(al);

        fillLabels();
                lblInfo.setText("Array List is not empty  Size = "+al.getSize()+" and Capacity is "+al.getCapacity());


    }//GEN-LAST:event_btnRemoveFirstActionPerformed

    private void btnRemoveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveLastActionPerformed
        al.remove();

        fillLabels();
        
                lblInfo.setText("Array List is not empty  Size = "+al.getSize()+" and Capacity is "+al.getCapacity());

    }//GEN-LAST:event_btnRemoveLastActionPerformed

    private void btnRemoveByIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveByIndexActionPerformed

        String indexStr = txtIndex.getText();

        if (indexStr.length() == 0) {
            JOptionPane.showMessageDialog(pnlMain, "Please enter the index");
        } else {

            int index = 0;

            try {
                index = Integer.parseInt(indexStr);

                al.remove(index);
            } catch (NumberFormatException | ArrayIndexOutOfBoundsException ex) {

                if (ex instanceof NumberFormatException) {
                    JOptionPane.showMessageDialog(pnlMain, "Please enter a valid index, a positive integer only");
                }

                if (ex instanceof ArrayIndexOutOfBoundsException) {
                    JOptionPane.showMessageDialog(pnlMain, "Index= " + index + ", size= " + al.getSize()
                            + ". Index must be less than the size");
                }

            }

            fillLabels();
                    lblInfo.setText("Array List is not empty  Size = "+al.getSize()+" and Capacity is "+al.getCapacity());

        }


    }//GEN-LAST:event_btnRemoveByIndexActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String value = txtValue.getText();

        int loc = -1;

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(pnlMain, "Please enter the value you want to search for");
        } else {

            loc = al.firstOccurenceOf(value);

            if (loc == -1) {
                JOptionPane.showMessageDialog(pnlMain, "The value " + value + " was not found in the list");

            } else {
                JOptionPane.showMessageDialog(pnlMain, "The value " + value + " is at index " + loc + " in the list");

            }

        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        al.clear();

        clearLabelsTexts();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayListDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayListDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddByIndex;
    private javax.swing.JButton btnAddFirst;
    private javax.swing.JButton btnAddLast;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemoveByIndex;
    private javax.swing.JButton btnRemoveFirst;
    private javax.swing.JButton btnRemoveLast;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValue;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtIndex;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
