
import ArrayList_based.MyStackAL;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fares Abu Ali
 */
public class StackVisualisation extends javax.swing.JFrame {

    JLabel[] lbls = new JLabel[10];
    JLabel lblPeek;
    int initial_Y = 400;
    int peekPointerLocation = initial_Y + 10;

    MyStackAL<Object> ms = new MyStackAL<>();

    public StackVisualisation() {

        initComponents();

        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Fares H.Abu Ali");
        createStackShape();

    }

    public void createStackShape() {

        lblPeek = new JLabel("Peek-->");
        lblPeek.setFont(new Font("Thoma", 1, 14));

        pnlMain.add(lblPeek, new AbsoluteConstraints(320, 370, 59, 20));// x,y,width,height

        lblPeek.setVisible(false);

        for (int i = 0; i < 10; i++) {
            lbls[i] = new JLabel();
            pnlMain.add(lbls[i], new AbsoluteConstraints(370, initial_Y, 59, 40));// x,y,width,height

            lbls[i].setHorizontalAlignment(0);

            lbls[i].setVisible(false);
            lbls[i].setBorder(new LineBorder(Color.black, 1));
            initial_Y -= 40;
        }

        //reset 
        initial_Y = 400;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtEnterToPush = new javax.swing.JTextField();
        btnPush = new javax.swing.JButton();
        lblEnter = new javax.swing.JLabel();
        btnPop = new javax.swing.JButton();
        pnlSizeAndPeek = new javax.swing.JPanel();
        lblTopValue = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtEnterToPush.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnPush.setBackground(new java.awt.Color(51, 51, 51));
        btnPush.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPush.setForeground(new java.awt.Color(255, 255, 255));
        btnPush.setText("PUSH");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        lblEnter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEnter.setText("Enter a value:-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtEnterToPush, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPush)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterToPush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPush))
                .addContainerGap())
        );

        pnlMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 70));

        btnPop.setBackground(new java.awt.Color(51, 51, 51));
        btnPop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPop.setForeground(new java.awt.Color(255, 255, 255));
        btnPop.setText("POP");
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });
        pnlMain.add(btnPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 70, -1));

        pnlSizeAndPeek.setBackground(new java.awt.Color(255, 255, 255));
        pnlSizeAndPeek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        lblTopValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTopValue.setText("Peek = ");

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSize.setText("Size = ");

        javax.swing.GroupLayout pnlSizeAndPeekLayout = new javax.swing.GroupLayout(pnlSizeAndPeek);
        pnlSizeAndPeek.setLayout(pnlSizeAndPeekLayout);
        pnlSizeAndPeekLayout.setHorizontalGroup(
            pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeAndPeekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlSizeAndPeekLayout.setVerticalGroup(
            pnlSizeAndPeekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSizeAndPeekLayout.createSequentialGroup()
                .addComponent(lblTopValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pnlMain.add(pnlSizeAndPeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 110));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Stack Visualization");
        pnlMain.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 30));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed

        String value = txtEnterToPush.getText();

        if (value.length() == 0) {
            JOptionPane.showMessageDialog(pnlMain, "Please Enter a value to push");
        } else if (ms.getSize() >= 10) {
            JOptionPane.showMessageDialog(pnlMain, "Stack is Full!!!");

        } else {

            if (ms.getSize() != 0) {
                peekPointerLocation -= 40;
            }

            System.out.println("Size=" + ms.getSize() + ", peekPointerLoc=" + peekPointerLocation);

            lbls[ms.getSize()].setText(value);
            lbls[ms.getSize()].setVisible(true);
            pnlMain.add(lblPeek, new AbsoluteConstraints(320, peekPointerLocation, 59, 20));//// x,y,width,height
            lblPeek.setVisible(true);

            ms.push(value);

            lblTopValue.setText("Peek = " + ms.getPeek());
            lblSize.setText("Size = " + ms.getSize());

        }
    }//GEN-LAST:event_btnPushActionPerformed

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed

        ms.pop();

        if (ms.getSize() == 0) {
            JOptionPane.showMessageDialog(pnlMain, "Stack is Empty!!");
            lbls[0].setText("");
            lbls[0].setVisible(false);
            lblTopValue.setText("Peek = null");
            lblSize.setText("Size = 0");
            lblPeek.setVisible(false);
        } else {
            lbls[ms.getSize()].setText("");
            lbls[ms.getSize()].setVisible(false);

            pnlMain.remove(lblPeek);

            peekPointerLocation += 40;

            pnlMain.add(lblPeek, new AbsoluteConstraints(320, peekPointerLocation + 1, 59, 20));
            lblPeek.setVisible(true);

            lblTopValue.setText("Peek = " + ms.getPeek());
            lblSize.setText("Size = " + ms.getSize());
        }

    }//GEN-LAST:event_btnPopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackVisualisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackVisualisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackVisualisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackVisualisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackVisualisation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTopValue;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlSizeAndPeek;
    private javax.swing.JTextField txtEnterToPush;
    // End of variables declaration//GEN-END:variables
}
