
import atm.ATM;
import atm.BankDatabase;
import atm.CashDispenser;
import atm.Deposit;
import atm.DepositSlot;
import atm.Keypad;
import atm.Screen;
import atm.Withdrawal;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.lang.model.util.SimpleAnnotationValueVisitor6;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Fares Abu Ali
 */
public class ATM2 extends javax.swing.JFrame {

    private boolean userAuthenticated = false;//the database authenticates a user by 
    //comparing the account number and PIN entered by the user with those of an account in the database. 
    private int currentAccountNumber;

    // references to associated objects
    private Screen screen;
    private Keypad keypad;
    private CashDispenser cashDispenser;
    private DepositSlot depositSlot;
    private BankDatabase bankDatabase;

    int whichTransaction = -1;
    //constants corresponding to main menu objects
    private static final int LOAN = 0;
    private static final int WITHDRAWAL = 1;
    private static final int DEPOSIT = 2;
    private static final int TRANSFER = 3;

    int loanCtr = 0;
    boolean justCheckTheAmountOfTransfer = false;
    int recipientAccountNum = 0;

    //--references for ENTER button---
    Withdrawal wit;

    public ATM2() {
        super("Automated Teller Machine (ATM) Software System    Developed By:Fares AbuAli  12th June 2019");
        initComponents();
        userAuthenticated = false;
        currentAccountNumber = 0;

        //Class ATM has Composition relationships with:
        screen = new Screen();
        keypad = new Keypad();
        cashDispenser = new CashDispenser();
        depositSlot = new DepositSlot();
        //so class ATM is responsible for their creation. --------------------------------------
        File myFile = new File("myBase");
        if (!myFile.exists()) {
            bankDatabase = new BankDatabase();
        }
        //[Note: If this were a real ATM system, the ATM class would receive a reference to an existing 
        //database object created by the bank. However, in this implementation we’re only simulating
        //the bank’s database, so class ATM creates the BankDatabase object with which it interacts.]
    }

    public BankDatabase getBankDatabase() {
        return bankDatabase;
    }

    public void welcomeUser(int currentAccountNumber) {
        File myFile = new File("myBase.txt");
        try {
            Scanner sc = new Scanner(myFile);

            while (sc.hasNext()) {
                String name = sc.next();
                if (Integer.parseInt(sc.next()) == currentAccountNumber) {
                    if (whichTransaction == TRANSFER) {
                        lblScreen1.setText("The recipient is: " + name);
                    } else {
                        lblScreen1.setText("Welcome, " + name);
                    }
                    break;
                }
                sc.nextLine();
            }

            //txtaReceipt.append("---");
        } catch (FileNotFoundException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblScreen1 = new javax.swing.JLabel();
        lblScreen2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnWithdraw = new javax.swing.JButton();
        btnLoann = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnEnterGreen = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnDeposit = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaReceipt = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();
        btnGetLoan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDecimalPoint = new javax.swing.JLabel();
        txtTotalPayment = new javax.swing.JTextField();
        txtInterest = new javax.swing.JTextField();
        txtYears = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtMonthlyPayment = new javax.swing.JTextField();
        btnDecimalPoint = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblNumber = new javax.swing.JLabel();
        lblNumberPrompt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblScreen1.setBackground(new java.awt.Color(204, 255, 204));
        lblScreen1.setFont(new java.awt.Font("Sukar", 1, 14)); // NOI18N
        lblScreen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblScreen2.setBackground(new java.awt.Color(204, 255, 204));
        lblScreen2.setFont(new java.awt.Font("Sukar", 1, 14)); // NOI18N
        lblScreen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblScreen1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
            .addComponent(lblScreen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblScreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScreen2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 340, 90));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LeftArrow.png"))); // NOI18N
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });
        jPanel4.add(btnWithdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 60));

        btnLoann.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LeftArrow.png"))); // NOI18N
        btnLoann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoannActionPerformed(evt);
            }
        });
        jPanel4.add(btnLoann, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 60));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Withdraw");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Loan");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 110, 180));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/one.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 80));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/two.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, 80));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/three.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 80));

        btnEnterGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enter.png"))); // NOI18N
        btnEnterGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterGreenActionPerformed(evt);
            }
        });
        jPanel5.add(btnEnterGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 110, 80));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/four.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 80));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/five.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 100, 80));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/six.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 100, 80));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seven.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 80));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eight.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, 80));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nine.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 80));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zero.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 80));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 110, 80));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 110, 80));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Create a New Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, 50));

        btnTransfer.setBackground(new java.awt.Color(0, 204, 204));
        btnTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTransfer.setText("Balance Transfer");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });
        jPanel5.add(btnTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 200, 50));

        btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exitAccount.png"))); // NOI18N
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 70, 70));

        jLabel10.setFont(new java.awt.Font("Sukar", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Exit Account");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 100, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 560, 430));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RigthArrow.png"))); // NOI18N
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });
        jPanel6.add(btnDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 60));

        btnBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RigthArrow.png"))); // NOI18N
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });
        jPanel6.add(btnBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Balance");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Deposit");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 180));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtaReceipt.setColumns(20);
        txtaReceipt.setRows(5);
        txtaReceipt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtaReceiptAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(txtaReceipt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 360, 258));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 83, 37));

        btnGetLoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGetLoan.setText("get");
        btnGetLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetLoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 85, 37));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 91, 37));

        btnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReceipt.setText("Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });
        jPanel1.add(btnReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, 37));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Interest Rate");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Number of years");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount of Loan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblDecimalPoint.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblDecimalPoint.setText("decimal point button for double numbers");
        jPanel1.add(lblDecimalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 210, -1));

        txtTotalPayment.setBackground(new java.awt.Color(204, 204, 204));
        txtTotalPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotalPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 120, 30));

        txtInterest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtInterest.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInterestActionPerformed(evt);
            }
        });
        txtInterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInterestKeyTyped(evt);
            }
        });
        jPanel1.add(txtInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, 30));

        txtYears.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtYears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearsActionPerformed(evt);
            }
        });
        jPanel1.add(txtYears, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 30));

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 30));

        txtMonthlyPayment.setBackground(new java.awt.Color(204, 204, 204));
        txtMonthlyPayment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMonthlyPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthlyPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtMonthlyPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 30));

        btnDecimalPoint.setBackground(new java.awt.Color(0, 204, 204));
        btnDecimalPoint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDecimalPoint.setText(".");
        btnDecimalPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalPointActionPerformed(evt);
            }
        });
        jPanel1.add(btnDecimalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 40, 37));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Monthly Payment");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 580, 620));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));

        lblNumber.setFont(new java.awt.Font("Sukar", 1, 14)); // NOI18N

        lblNumberPrompt.setFont(new java.awt.Font("Sukar", 1, 14)); // NOI18N
        lblNumberPrompt.setText("Enter your account number:-");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumberPrompt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblNumberPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 340, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String enteredNumber = lblNumber.getText() + "1";
        lblNumber.setText(enteredNumber);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        String enteredNumber = lblNumber.getText() + "2";
        lblNumber.setText(enteredNumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String enteredNumber = lblNumber.getText() + "3";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    boolean enteredToTheUserAccount = false;
    boolean trueUserPIN = false;
    boolean chooseAmountOfWithdrawalMode = false;
    private void btnEnterGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterGreenActionPerformed

        if (!enteredToTheUserAccount) {

            if (lblNumber.getText().length() > 0) {
                int enteredAccountNumber = Integer.parseInt(lblNumber.getText());
                if (bankDatabase.getAccount(enteredAccountNumber) != null) {
                    currentAccountNumber = enteredAccountNumber;
                    welcomeUser(currentAccountNumber);
                    lblNumber.setText("");
                    lblNumberPrompt.setText("Enter your PIN:- ");
//                btnLoann.setEnabled(true);
//                btnWithdraw.setEnabled(true);
//                btnDeposit.setEnabled(true);
//                btnBalance.setEnabled(true);
                    enteredToTheUserAccount = true;
                } else {
                    lblNumber.setText("No such account number in the bank database");
                }
            }
        } else if (!trueUserPIN) {

            if (lblNumber.getText().length() > 0) {
                int enteredPIN = Integer.parseInt(lblNumber.getText());

                userAuthenticated = bankDatabase.authenticateUser(currentAccountNumber, enteredPIN);

                if (!userAuthenticated) {
                    lblScreen1.setText("Wrong PIN");
                    //enteredPIN = Integer.parseInt(lblNumber.getText());
                    lblNumber.setText("");
                } else {

                    trueUserPIN = true;
                    lblScreen1.setText("PIN authenticated successuflly");
                    lblScreen2.setText("You can do transactions now");
                    btnLoann.setEnabled(true);
                    btnWithdraw.setEnabled(true);
                    btnDeposit.setEnabled(true);
                    btnBalance.setEnabled(true);
                    lblNumber.setText("");
                }
            }

        } else if (whichTransaction == DEPOSIT) {
            Deposit dep = new Deposit(currentAccountNumber, bankDatabase);
            int depositAmount = 0;
            if (lblNumber.getText().length() > 0) {
                depositAmount = Integer.parseInt(lblNumber.getText());
            }
            bankDatabase.credit(dep.getAccountNumber(), depositAmount);

            //----NOW THE BALANCE HAS BEEN UPDATED,SO WE MUST UPDATE THE FILE"S DATA ALSO------
            dep.updateUsersDataInTheClientsFile();
            //--NOW I WILL REWRITE OVER THE OLD DATA----
            bankDatabase.rewriteTheAllClientsFile();

            lblScreen1.setText("Your envelope has been accepted");
            lblScreen2.setText("");
            lblNumber.setText("The cash has been added to your account successfully");

        } else if (whichTransaction == WITHDRAWAL) {

            if (wit == null) {
                wit = new Withdrawal(currentAccountNumber, bankDatabase);
                chooseAmountOfWithdrawalMode = true;// now if you enter ENTER again, it will show you the amountOfWithdrawalMode
            }

            if (chooseAmountOfWithdrawalMode) {

                int withdrawalAmount = 0;
                if (lblNumber.getText().length() > 0) {
                    withdrawalAmount = Integer.parseInt(lblNumber.getText());

                    int[] availableWithdrawalAmounts = {20, 40, 60, 100, 200};
                    if (Arrays.binarySearch(availableWithdrawalAmounts, withdrawalAmount) < 0) {
                        lblNumberPrompt.setText("Please choose one of the following amounts only");
                        lblNumber.setText("");
                    } else if (bankDatabase.getAccount(currentAccountNumber).getAvailableBalance() < withdrawalAmount) {
                        lblScreen1.setText("Sorry, Insufficient cash in your account");
                        lblScreen2.setText("Try to withdraw a smaller amount");

                    } else {

                        Deposit dep = new Deposit(recipientAccountNum, bankDatabase);
                        bankDatabase.debit(wit.getAccountNumber(), withdrawalAmount);

                        //----NOW THE BALANCE HAS BEEN UPDATED,SO WE MUST UPDATE THE FILE"S DATA ALSO------
                        wit.updateUsersDataInTheClientsFile();
                        //--NOW I WILL REWRITE OVER THE OLD DATA----
                        bankDatabase.rewriteTheAllClientsFile();

                        lblScreen1.setText("Cash withdrawed successfully,");
                        lblScreen2.setText(" take them from the dispenser");
                        lblNumber.setText("");

                    }
                } else {
                    lblScreen1.setText("You didn't enter the amount yet");
                    lblScreen2.setText("");
                }

            }

        }//end of withdrawing
        else if (whichTransaction == TRANSFER) {

            if (justCheckTheAmountOfTransfer) {

                int withdrawalAmount = 0;
                if (lblNumber.getText().length() > 0) {
                    withdrawalAmount = Integer.parseInt(lblNumber.getText());

                    if (bankDatabase.getAccount(currentAccountNumber).getAvailableBalance() < withdrawalAmount) {
                        lblScreen1.setText("Sorry, Insufficient cash in your account");
                        lblScreen2.setText("Try to transfer a smaller amount");
                    } else {
                        wit = new Withdrawal(currentAccountNumber, bankDatabase);
                        bankDatabase.debit(wit.getAccountNumber(), withdrawalAmount);

                        //----NOW THE BALANCE HAS BEEN UPDATED,SO WE MUST UPDATE THE FILE"S DATA ALSO------
                        wit.updateUsersDataInTheClientsFile();
                        //--NOW I WILL REWRITE OVER THE OLD DATA----
                        bankDatabase.rewriteTheAllClientsFile();
//==================================================================================================

                        Deposit dep = new Deposit(recipientAccountNum, bankDatabase);
                        //NOW JUST YOU HAVE TO CREDIT THIS AMOUNT TO THE RECIPIENT"S ACCOUNT
                        bankDatabase.credit(recipientAccountNum, withdrawalAmount);

                        //----NOW THE BALANCE HAS BEEN UPDATED,SO WE MUST UPDATE THE FILE"S DATA ALSO------
                        dep.updateUsersDataInTheClientsFile();
                        //--NOW I WILL REWRITE OVER THE OLD DATA----
                        bankDatabase.rewriteTheAllClientsFile();

                        lblScreen1.setText("Cash Transferd successfully");
                        lblScreen2.setText(" to the recipient's account");
                        lblNumber.setText("");
                    }
                } else {
                    lblScreen1.setText("You didn't enter the amount yet");
                    lblScreen2.setText("");
                }

            } else {
                if (lblNumber.getText().length() > 0) {

                    recipientAccountNum = Integer.parseInt(lblNumber.getText());

                    if (bankDatabase.getAccount(recipientAccountNum) == null) {
                        lblScreen1.setText("The entered number doesn't exist ");
                        lblScreen2.setText("in the bank's database");
                    } else {
                        lblNumber.setText("");
                        lblNumberPrompt.setText("OK, enter the amount you want to transfer:-");
                        welcomeUser(recipientAccountNum);
                        justCheckTheAmountOfTransfer = true;
                    }
                } else {
                    lblScreen1.setText("You didn't enter the amount yet");
                    lblScreen2.setText("");
                }
            }

        } else if (whichTransaction == LOAN) {

            if (lblNumber.getText().length() > 0) {

                if (loanCtr == 0) {
                    txtInterest.setText(lblNumber.getText());
                    lblNumber.setText("");
                    lblNumberPrompt.setText("Enter the number of years");
                    loanCtr++;
                } else if (loanCtr == 1) {
                    txtYears.setText(lblNumber.getText());
                    lblNumber.setText("");
                    lblNumberPrompt.setText("Enter the amount of loan");
                    loanCtr++;
                } else if (loanCtr == 2) {
                    txtAmount.setText(lblNumber.getText());
                    lblNumber.setText("");
                    lblNumberPrompt.setText("");
                    lblScreen1.setText("click the\"get\" button to ");
                    lblScreen2.setText("print the receipt");
                    whichTransaction = -1;
                    loanCtr = 0;
                }

            } else {
                lblScreen1.setText("You didn't enter the amount yet");
                lblScreen2.setText("");
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterGreenActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String enteredNumber = lblNumber.getText() + "4";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String enteredNumber = lblNumber.getText() + "5";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String enteredNumber = lblNumber.getText() + "6";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String enteredNumber = lblNumber.getText() + "7";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        String enteredNumber = lblNumber.getText() + "8";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        String enteredNumber = lblNumber.getText() + "9";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        String enteredNumber = lblNumber.getText() + "0";
        lblNumber.setText(enteredNumber);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    JFrame frameC;
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

        lblNumberPrompt.setText("");
        lblScreen1.setText("PIN authenticated successfully");
        lblScreen2.setText("You can do transactions now");
//        frameC = new JFrame("Exit");
//        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "ATM System",
//                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
//            System.exit(0);
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

//        btnLoan.setEnabled(false);
//        btnReset.setEnabled(false);
//        btnExit.setEnabled(false);
//        btnReceipt.setEnabled(false);
//
//        btnLoann.setEnabled(false);
//        btnWithdraw.setEnabled(false);
//        btnDeposit.setEnabled(false);
//        btnBalance.setEnabled(false);
        lblNumber.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        lblNumberPrompt.setText("Enter the amount of withdrawal");
        whichTransaction = WITHDRAWAL;
        chooseAmountOfWithdrawalMode = true;
        lblNumberPrompt.setText("Enter the amount of withdrawal:- ");
        lblNumber.setText("");
        lblScreen1.setText("$20  $40  $60");
        lblScreen2.setText("$100   $200");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnLoannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoannActionPerformed

        btnReceipt.setEnabled(true);
        btnExit.setEnabled(true);
        btnReset.setEnabled(true);
        btnGetLoan.setEnabled(true);
        btnDecimalPoint.setEnabled(true);
        txtInterest.setEnabled(true);
        txtYears.setEnabled(true);
        txtAmount.setEnabled(true);
        txtMonthlyPayment.setEnabled(true);
        txtTotalPayment.setEnabled(true);

        whichTransaction = LOAN;

        lblNumberPrompt.setText("Enter the Interest Rate");
        lblNumber.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoannActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        //int amount = 0;

        lblNumberPrompt.setText("Enter the amount of deposit");
        whichTransaction = DEPOSIT;
        lblScreen1.setText("Waiting you to insert the cash");
        lblScreen2.setText("to the deposit slot");
        lblNumber.setText("");
        

//        try {
//            Thread.sleep(7000);
//        } catch (InterruptedException ex) {
//
//        }

    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed

        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
        tDate.format(timer.getTime());
        //------------------------------------------------
        String clientName = "";
        int pin = 0;
        double cash = 0;

        File myFile = new File("myBase.txt");
        try {
            Scanner sc = new Scanner(myFile);

            while (sc.hasNext()) {
                clientName = sc.next();
                if (Integer.parseInt(sc.next()) == currentAccountNumber) {
                    pin = Integer.parseInt(sc.next());
                    cash = Double.parseDouble(sc.next());
                    break;
                }
                sc.nextLine();
            }
        } catch (FileNotFoundException ex) {

        }

        txtaReceipt.append("\tClient Balance Inquiry:-\n"
                + "\n============================================\t"
                + "\nClient's Name:\t\t\t" + clientName
                + "\nAccount Number:\t\t" + currentAccountNumber
                + "\nPersonal Identification Number (PIN):\t" + pin
                + "\nAvailable Balance:\t\t$" + cash
                + "\n============================================\t"
                + "\nDate: " + tDate.format(timer.getTime())
                + "\t\tTime: " + tTime.format(timer.getTime())
                + "\n\n\t\tThank you\n"
                + "-------------------------------------CUT HERE------------------------------------\n");


    }//GEN-LAST:event_btnBalanceActionPerformed

    JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed

        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit the LOAN mode", "Loan Management Systems",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            //System.exit(0);
            btnReceipt.setEnabled(true);
            btnExit.setEnabled(true);
            btnReset.setEnabled(true);
            btnGetLoan.setEnabled(true);
            btnDecimalPoint.setEnabled(true);
            txtInterest.setEnabled(true);
            txtYears.setEnabled(true);
            txtAmount.setEnabled(true);
            txtMonthlyPayment.setEnabled(true);
            txtTotalPayment.setEnabled(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        btnGetLoan.setEnabled(false);
        btnReset.setEnabled(false);
        btnExit.setEnabled(false);
        btnReceipt.setEnabled(false);
        btnDecimalPoint.setEnabled(false);

        btnLoann.setEnabled(false);
        btnWithdraw.setEnabled(false);
        btnDeposit.setEnabled(false);
        btnBalance.setEnabled(false);
        txtInterest.setEnabled(false);
        txtYears.setEnabled(false);
        txtAmount.setEnabled(false);
        txtMonthlyPayment.setEnabled(false);
        txtTotalPayment.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtInterest.setText("");
        txtAmount.setText("");
        txtYears.setText("");
        txtMonthlyPayment.setText("");
        txtTotalPayment.setText("");
        txtaReceipt.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed

        String annualInterestRate = String.format(txtInterest.getText());
        String numberOfYears = String.format(txtYears.getText());
        String loanAmount = String.format(txtAmount.getText());

        String monthlyPayment = String.format(txtMonthlyPayment.getText());
        String totalPayment = String.format(txtTotalPayment.getText());

        int refs = 1325 + (int) (Math.random() * 4238);
        //------------------------------------------------
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
        tDate.format(timer.getTime());
        //------------------------------------------------

        txtaReceipt.append("\tLoan Management System\n"
                + "Reference:\t\t" + refs
                + "\n==========================================\t"
                + "\nInterest Rate:\t\t\t" + annualInterestRate
                + "\nRepayment Years:\t\t" + numberOfYears
                + "\nAmount of Loan:\t\t" + "$" + loanAmount
                + "\nMonthly Payment:\t\t" + monthlyPayment
                + "\nTotal Payment:\t\t" + totalPayment
                + "\n==========================================\t"
                + "\nDate: " + tDate.format(timer.getTime())
                + "\t\tTime: " + tTime.format(timer.getTime())
                + "\n\n\t\tThank you\n");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnReceiptActionPerformed

    private void txtTotalPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPaymentActionPerformed

    private void txtInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInterestActionPerformed

    private void txtYearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearsActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearsActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtMonthlyPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthlyPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthlyPaymentActionPerformed

    private void btnGetLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetLoanActionPerformed
        double annualInterestRate = Double.parseDouble(txtInterest.getText());
        double monthlyInterestRate = annualInterestRate / 1200;
        int numberOfYears = Integer.parseInt(txtYears.getText());
        double loanAmount = Double.parseDouble(txtAmount.getText());
        //------------------------------------------------------------------

        double monthlyPayment = loanAmount * monthlyInterestRate / (1 - 1 / Math.pow(1 + monthlyInterestRate, numberOfYears * 12));
        String imonthlyPayment = Double.toString(monthlyPayment);
        imonthlyPayment = String.format("$%.2f", monthlyPayment);
        txtMonthlyPayment.setText(imonthlyPayment);

        double totalPayment = monthlyPayment * numberOfYears * 12;
        String itotalPayment = String.format("$%.2f", totalPayment);
        txtTotalPayment.setText(itotalPayment);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetLoanActionPerformed

    private void txtInterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInterestKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_txtInterestKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        RegisterInterface ri = new RegisterInterface(getBankDatabase());
        // I mad an object of class RegisterInterface
        // so whenever I click the button"create" it will let the frame pop up 

        //System.out.println(ri.theNewUserName);
        //System.out.println(ri.theNewUserPIN);
        // bankDatabase.addAccount(ri.theNewUserName,ri.theNewUserPIN);
//        System.out.println("I am in ATM2 class");
//        System.out.println(theUserNameComingFromTheRegistrationForm);
//        System.out.println(theUserPINComingFromTheRegistrationForm);
//        
//        
//        bankDatabase.addAccount(theUserNameComingFromTheRegistrationForm, theUserPINComingFromTheRegistrationForm);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed

        if (userAuthenticated) {
            lblNumberPrompt.setText("Enter the recepient's account number:-");
            lblScreen1.setText("Enter the recepient's account number:-");
            lblScreen2.setText("");
            whichTransaction = TRANSFER;
        }


    }//GEN-LAST:event_btnTransferActionPerformed

    private void txtaReceiptAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtaReceiptAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaReceiptAncestorAdded

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed

        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to close your account", "ATM System",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            lblNumberPrompt.setText("Enter your account number:-");
            btnGetLoan.setEnabled(false);
            btnReset.setEnabled(false);
            btnExit.setEnabled(false);
            btnReceipt.setEnabled(false);

            btnLoann.setEnabled(false);
            btnWithdraw.setEnabled(false);
            btnDeposit.setEnabled(false);
            btnBalance.setEnabled(false);
            lblNumber.setText("");
            lblScreen1.setText("");
            lblScreen2.setText("");

            enteredToTheUserAccount = false;
            trueUserPIN = false;
            chooseAmountOfWithdrawalMode = false;
            loanCtr = 0;
            justCheckTheAmountOfTransfer = false;
            recipientAccountNum = 0;
            whichTransaction=-1;

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnDecimalPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalPointActionPerformed
        lblNumber.setText(lblNumber.getText() + ".");
    }//GEN-LAST:event_btnDecimalPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                ATM2 start = new ATM2();
                start.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnDecimalPoint;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnEnterGreen;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetLoan;
    private javax.swing.JButton btnLoann;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDecimalPoint;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblNumberPrompt;
    private javax.swing.JLabel lblScreen1;
    private javax.swing.JLabel lblScreen2;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtInterest;
    private javax.swing.JTextField txtMonthlyPayment;
    private javax.swing.JTextField txtTotalPayment;
    private javax.swing.JTextField txtYears;
    private javax.swing.JTextArea txtaReceipt;
    // End of variables declaration//GEN-END:variables
}
