
import atm.BankDatabase;
import java.awt.ComponentOrientation;
import javax.swing.JButton;
import javax.swing.JFrame;
import atm.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fares Abu Ali
 */
public class RegisterInterface extends javax.swing.JFrame {

    String theNewUserName;
    int theNewUserPIN;
    private BankDatabase bankDatabase;

    public RegisterInterface() {
        setUndecorated(true);
        setLocation(150, 150);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
        initComponents();
    }

    public RegisterInterface(BankDatabase bankdatabase) {
        setUndecorated(true);
        setLocation(150, 150);

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        this.bankDatabase = bankdatabase;
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnA16 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnA6 = new javax.swing.JButton();
        btnA7 = new javax.swing.JButton();
        btnA8 = new javax.swing.JButton();
        btnA9 = new javax.swing.JButton();
        btnA10 = new javax.swing.JButton();
        btnA11 = new javax.swing.JButton();
        btnA13 = new javax.swing.JButton();
        btnA14 = new javax.swing.JButton();
        btnA15 = new javax.swing.JButton();
        btnA17 = new javax.swing.JButton();
        btnA18 = new javax.swing.JButton();
        btnA19 = new javax.swing.JButton();
        btnA20 = new javax.swing.JButton();
        btnA21 = new javax.swing.JButton();
        btnA22 = new javax.swing.JButton();
        btnA23 = new javax.swing.JButton();
        btnA24 = new javax.swing.JButton();
        btnA25 = new javax.swing.JButton();
        btnA26 = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnA1 = new javax.swing.JButton();
        btnA12 = new javax.swing.JButton();
        btnCleaR1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlKeypad = new javax.swing.JPanel();
        kbtn1 = new javax.swing.JButton();
        kbtn2 = new javax.swing.JButton();
        kbtn4 = new javax.swing.JButton();
        kbtn5 = new javax.swing.JButton();
        kbtn6 = new javax.swing.JButton();
        kbtn7 = new javax.swing.JButton();
        kbtn8 = new javax.swing.JButton();
        kbtn9 = new javax.swing.JButton();
        kbtn10 = new javax.swing.JButton();
        btnCleaR = new javax.swing.JButton();
        kbtn3 = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnDispose = new javax.swing.JButton();
        txtNameRegister = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPIN_Register = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnA16.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA16.setText("A");
        btnA16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA16ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA16, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 96, -1, 0));

        btnA2.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA2.setText("C");
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 52, 41));

        btnA3.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA3.setText("D");
        btnA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 52, 41));

        btnA4.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA4.setText("E");
        btnA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 52, 41));

        btnA5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA5.setText("G");
        btnA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 52, 41));

        btnA6.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA6.setText("F");
        btnA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 52, 41));

        btnA7.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA7.setText("H");
        btnA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 52, 41));

        btnA8.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA8.setText("I");
        btnA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 52, 41));

        btnA9.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA9.setText("J");
        btnA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 52, 41));

        btnA10.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA10.setText("K");
        btnA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 52, 41));

        btnA11.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA11.setText("L");
        btnA11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 52, 41));

        btnA13.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA13.setText("M");
        btnA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA13ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 52, 41));

        btnA14.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA14.setText("O");
        btnA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA14ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 52, 41));

        btnA15.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA15.setText("P");
        btnA15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA15ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 52, 41));

        btnA17.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA17.setText("Q");
        btnA17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA17ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 52, 41));

        btnA18.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA18.setText("R");
        btnA18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA18ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 52, 41));

        btnA19.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA19.setText("S");
        btnA19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA19ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 52, 41));

        btnA20.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA20.setText("T");
        btnA20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA20ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 52, 41));

        btnA21.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA21.setText("U");
        btnA21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA21ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 52, 41));

        btnA22.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA22.setText("V");
        btnA22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA22ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 52, 41));

        btnA23.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA23.setText("W");
        btnA23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA23ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 52, 41));

        btnA24.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA24.setText("X");
        btnA24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA24ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 52, 41));

        btnA25.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA25.setText("Y");
        btnA25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA25ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 52, 41));

        btnA26.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA26.setText("Z");
        btnA26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA26ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 52, 41));

        btnA.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        jPanel1.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 52, 41));

        btnA1.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA1.setText("B");
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 52, 41));

        btnA12.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnA12.setText("N");
        btnA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA12ActionPerformed(evt);
            }
        });
        jPanel1.add(btnA12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 52, 41));

        btnCleaR1.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnCleaR1.setText("Clear");
        btnCleaR1.setToolTipText("");
        btnCleaR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleaR1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCleaR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 610, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlKeypad.setBackground(new java.awt.Color(255, 51, 51));
        pnlKeypad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        kbtn1.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn1.setText("1");
        kbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kbtn1MouseClicked(evt);
            }
        });
        kbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn1ActionPerformed(evt);
            }
        });

        kbtn2.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn2.setText("2");
        kbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn2ActionPerformed(evt);
            }
        });

        kbtn4.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn4.setText("4");
        kbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn4ActionPerformed(evt);
            }
        });

        kbtn5.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn5.setText("5");
        kbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn5ActionPerformed(evt);
            }
        });

        kbtn6.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn6.setText("6");
        kbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn6ActionPerformed(evt);
            }
        });

        kbtn7.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn7.setText("7");
        kbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn7ActionPerformed(evt);
            }
        });

        kbtn8.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn8.setText("8");
        kbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn8ActionPerformed(evt);
            }
        });

        kbtn9.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn9.setText("9");
        kbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn9ActionPerformed(evt);
            }
        });

        kbtn10.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn10.setText("0");
        kbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn10ActionPerformed(evt);
            }
        });

        btnCleaR.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnCleaR.setText("Clear");
        btnCleaR.setToolTipText("");
        btnCleaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleaRActionPerformed(evt);
            }
        });

        kbtn3.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        kbtn3.setText("3");
        kbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKeypadLayout = new javax.swing.GroupLayout(pnlKeypad);
        pnlKeypad.setLayout(pnlKeypadLayout);
        pnlKeypadLayout.setHorizontalGroup(
            pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKeypadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKeypadLayout.createSequentialGroup()
                        .addComponent(kbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKeypadLayout.createSequentialGroup()
                        .addComponent(kbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlKeypadLayout.createSequentialGroup()
                        .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlKeypadLayout.createSequentialGroup()
                                .addComponent(kbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCleaR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKeypadLayout.setVerticalGroup(
            pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKeypadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlKeypadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleaR, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnlKeypad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.setToolTipText("");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnDispose.setBackground(new java.awt.Color(0, 0, 0));
        btnDispose.setFont(new java.awt.Font("Sukar", 1, 18)); // NOI18N
        btnDispose.setForeground(new java.awt.Color(255, 255, 255));
        btnDispose.setText("Exit");
        btnDispose.setToolTipText("");
        btnDispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisposeActionPerformed(evt);
            }
        });
        jPanel2.add(btnDispose, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        txtNameRegister.setBackground(new java.awt.Color(255, 51, 51));
        txtNameRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNameRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtNameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(txtNameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Enter your Name:-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\ATM icons\\rsz_redatm.png")); // NOI18N
        jLabel4.setText("Create a New Account :-");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, 70));

        txtPIN_Register.setBackground(new java.awt.Color(255, 51, 51));
        txtPIN_Register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPIN_Register.setForeground(new java.awt.Color(255, 255, 255));
        txtPIN_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIN_RegisterActionPerformed(evt);
            }
        });
        jPanel2.add(txtPIN_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("New Client? Welcome to our bank");
        jLabel3.setToolTipText("");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Make a PIN for your account:-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Glad to see you here :)");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA16ActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAActionPerformed

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA5ActionPerformed

    private void btnA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA6ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA6ActionPerformed

    private void btnA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA7ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA7ActionPerformed

    private void btnA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA8ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA8ActionPerformed

    private void btnA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA9ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA9ActionPerformed

    private void btnA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA10ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA10ActionPerformed

    private void btnA11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA11ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA11ActionPerformed

    private void btnA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA12ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA12ActionPerformed

    private void btnA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA13ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA13ActionPerformed

    private void btnA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA14ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA14ActionPerformed

    private void btnA15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA15ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA15ActionPerformed

    private void btnA17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA17ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA17ActionPerformed

    private void btnA18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA18ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA18ActionPerformed

    private void btnA19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA19ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA19ActionPerformed

    private void btnA20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA20ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA20ActionPerformed

    private void btnA21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA21ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA21ActionPerformed

    private void btnA22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA22ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA22ActionPerformed

    private void btnA23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA23ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA23ActionPerformed

    private void btnA24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA24ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA24ActionPerformed

    private void btnA25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA25ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA25ActionPerformed

    private void btnA26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA26ActionPerformed
        String letter = ((JButton) evt.getSource()).getText();
        txtNameRegister.setText(txtNameRegister.getText() + letter);        // TODO add your handling code here:
    }//GEN-LAST:event_btnA26ActionPerformed

    private void kbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtn1MouseClicked

    private void kbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn1ActionPerformed
        
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);

        // txtPassword.setText(txtPassword.getPassword() + buttonContent);
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtn1ActionPerformed

    private void kbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn2ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        // txtPassword.setText(txtPassword.getPassword() + buttonContent);

    }//GEN-LAST:event_kbtn2ActionPerformed

    private void kbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn4ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);

        //txtPassword.setText(txtPassword.getPassword() + buttonContent);
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtn4ActionPerformed

    private void kbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn5ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        //  txtPassword.setText(txtPassword.getPassword() + buttonContent);
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtn5ActionPerformed

    private void kbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn6ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        //  txtPassword.setText(txtPassword.getPassword() + buttonContent);
// TODO add your handling code here:
    }//GEN-LAST:event_kbtn6ActionPerformed

    private void kbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn7ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        // txtPassword.setText(txtPassword.getPassword() + buttonContent);
// TODO add your handling code here:
    }//GEN-LAST:event_kbtn7ActionPerformed

    private void kbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn8ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        //  txtPassword.setText(txtPassword.getPassword() + buttonContent);
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtn8ActionPerformed

    private void kbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn9ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        // txtPassword.setText(txtPassword.getPassword() + buttonContent);
// TODO add your handling code here:
    }//GEN-LAST:event_kbtn9ActionPerformed

    private void kbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn10ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent);
        //  txtPassword.setText(txtPassword.getPassword() + buttonContent);
// TODO add your handling code here:
    }//GEN-LAST:event_kbtn10ActionPerformed

    private void btnCleaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleaRActionPerformed

        txtPIN_Register.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleaRActionPerformed

    private void kbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtn3ActionPerformed
        String buttonContent = ((JButton) evt.getSource()).getText();
        txtPIN_Register.setText(txtPIN_Register.getText() + buttonContent); 
        //txtPassword.setText(txtPIN_Register.getText() + buttonContent);
       
// TODO add your handling code here:
    }//GEN-LAST:event_kbtn3ActionPerformed

    private void txtNameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameRegisterActionPerformed

    private void txtPIN_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIN_RegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPIN_RegisterActionPerformed

    private void btnCleaR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleaR1ActionPerformed

        txtNameRegister.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleaR1ActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        theNewUserName = txtNameRegister.getText();
        if (txtPIN_Register.getText().length() > 0) {
            theNewUserPIN = Integer.parseInt(txtPIN_Register.getText());

            System.out.println("Now I am in the registration interface and ");
            System.out.println(theNewUserName);
            System.out.println(theNewUserPIN);

            // BankDatabase bankDatbase= obj.getBankDatabase();
            bankDatabase.addAccount(theNewUserName, theNewUserPIN);

//        
//        ATM2.theUserNameComingFromTheRegistrationForm=theNewUserName;
//        ATM2.theUserPINComingFromTheRegistrationForm=theNewUserPIN;
//        
//        
//        System.out.println("I am in the interface and :");
//        System.out.println(ATM2.theUserNameComingFromTheRegistrationForm);
//        System.out.println( ATM2.theUserPINComingFromTheRegistrationForm);
//        //System.out.println(theNewUserName);
//        //System.out.println(theNewUserPIN);
//        
            int number = 10000 - bankDatabase.numberOfClients + 1;
            JOptionPane.showMessageDialog(btnDispose, "Your Account Number is: " + number, "Your Account Number", 1);
            dispose();

        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnDisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisposeActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisposeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA10;
    private javax.swing.JButton btnA11;
    private javax.swing.JButton btnA12;
    private javax.swing.JButton btnA13;
    private javax.swing.JButton btnA14;
    private javax.swing.JButton btnA15;
    private javax.swing.JButton btnA16;
    private javax.swing.JButton btnA17;
    private javax.swing.JButton btnA18;
    private javax.swing.JButton btnA19;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA20;
    private javax.swing.JButton btnA21;
    private javax.swing.JButton btnA22;
    private javax.swing.JButton btnA23;
    private javax.swing.JButton btnA24;
    private javax.swing.JButton btnA25;
    private javax.swing.JButton btnA26;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnA5;
    private javax.swing.JButton btnA6;
    private javax.swing.JButton btnA7;
    private javax.swing.JButton btnA8;
    private javax.swing.JButton btnA9;
    private javax.swing.JButton btnCleaR;
    private javax.swing.JButton btnCleaR1;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDispose;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kbtn1;
    private javax.swing.JButton kbtn10;
    private javax.swing.JButton kbtn2;
    private javax.swing.JButton kbtn3;
    private javax.swing.JButton kbtn4;
    private javax.swing.JButton kbtn5;
    private javax.swing.JButton kbtn6;
    private javax.swing.JButton kbtn7;
    private javax.swing.JButton kbtn8;
    private javax.swing.JButton kbtn9;
    private javax.swing.JPanel pnlKeypad;
    private javax.swing.JTextField txtNameRegister;
    private javax.swing.JTextField txtPIN_Register;
    // End of variables declaration//GEN-END:variables
}
