
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Fares Abu Ali
 */
public class GPA_Visual extends javax.swing.JFrame {

    DecimalFormat df = new DecimalFormat("#.#");

    /**
     * Creates new form GPA_Visual
     */
    public GPA_Visual() {
        initComponents();

        setTitle("GPA Calculator");
        
        setSize(745, 494);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtField6 = new javax.swing.JTextField();
        pnlMain = new javax.swing.JPanel();
        txtField0 = new javax.swing.JTextField();
        txtField1 = new javax.swing.JTextField();
        txtField2 = new javax.swing.JTextField();
        txtField3 = new javax.swing.JTextField();
        txtField4 = new javax.swing.JTextField();
        txtField5 = new javax.swing.JTextField();
        txtField7 = new javax.swing.JTextField();
        txtField8 = new javax.swing.JTextField();
        cmbo0 = new javax.swing.JComboBox<>();
        cmbo1 = new javax.swing.JComboBox<>();
        cmbo2 = new javax.swing.JComboBox<>();
        cmbo3 = new javax.swing.JComboBox<>();
        cmbo4 = new javax.swing.JComboBox<>();
        cmbo5 = new javax.swing.JComboBox<>();
        cmbo6 = new javax.swing.JComboBox<>();
        cmbo7 = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        txtFieldPreviousGPA = new javax.swing.JTextField();
        txtFieldFinishedHours = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblShowGPA = new javax.swing.JLabel();
        lblShowHrs = new javax.swing.JLabel();

        txtField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField6KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField6KeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBackground(new java.awt.Color(255, 102, 102));
        pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 6));
        pnlMain.setAutoscrolls(true);
        pnlMain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtField0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField0KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField0KeyTyped(evt);
            }
        });

        txtField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField1KeyTyped(evt);
            }
        });

        txtField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField2KeyTyped(evt);
            }
        });

        txtField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField3KeyTyped(evt);
            }
        });

        txtField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField4KeyTyped(evt);
            }
        });

        txtField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField5KeyTyped(evt);
            }
        });

        txtField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField7KeyTyped(evt);
            }
        });

        txtField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtField8KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtField8KeyTyped(evt);
            }
        });

        cmbo0.setBackground(new java.awt.Color(153, 153, 153));
        cmbo0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo0ActionPerformed(evt);
            }
        });

        cmbo1.setBackground(new java.awt.Color(153, 153, 153));
        cmbo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo1ActionPerformed(evt);
            }
        });

        cmbo2.setBackground(new java.awt.Color(153, 153, 153));
        cmbo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo2ActionPerformed(evt);
            }
        });

        cmbo3.setBackground(new java.awt.Color(153, 153, 153));
        cmbo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo3ActionPerformed(evt);
            }
        });

        cmbo4.setBackground(new java.awt.Color(153, 153, 153));
        cmbo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo4ActionPerformed(evt);
            }
        });

        cmbo5.setBackground(new java.awt.Color(153, 153, 153));
        cmbo5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo5ActionPerformed(evt);
            }
        });

        cmbo6.setBackground(new java.awt.Color(153, 153, 153));
        cmbo6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo6ActionPerformed(evt);
            }
        });

        cmbo7.setBackground(new java.awt.Color(153, 153, 153));
        cmbo7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbo7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbo7ActionPerformed(evt);
            }
        });

        btnCalculate.setBackground(new java.awt.Color(255, 255, 255));
        btnCalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtFieldPreviousGPA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFieldPreviousGPA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldPreviousGPA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldPreviousGPAKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldPreviousGPAKeyTyped(evt);
            }
        });

        txtFieldFinishedHours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFieldFinishedHours.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFieldFinishedHours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldFinishedHoursKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFieldFinishedHoursKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Previous GPA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Earned Hours:");

        lblShowGPA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblShowGPA.setForeground(new java.awt.Color(255, 255, 255));

        lblShowHrs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblShowHrs.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblShowGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cmbo5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtField5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cmbo0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtField0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblShowHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cmbo6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtField7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cmbo1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(cmbo7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtField8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cmbo2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addComponent(cmbo3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtFieldPreviousGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(392, 392, 392)
                        .addComponent(cmbo4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtField4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(txtFieldFinishedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnCalculate)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmbo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtField5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(cmbo0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtField0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cmbo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtField7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cmbo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmbo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldPreviousGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldFinishedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtField0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField0KeyPressed

        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }
    }//GEN-LAST:event_txtField0KeyPressed

    private void txtField0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField0KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField0KeyTyped

    private void txtField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField1KeyPressed

    }//GEN-LAST:event_txtField1KeyPressed

    private void txtField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField1KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField1KeyTyped

    private void txtField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField2KeyPressed

    private void txtField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField2KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField2KeyTyped

    private void txtField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField3KeyPressed

    private void txtField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField3KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField3KeyTyped

    private void txtField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField4KeyPressed

    private void txtField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField4KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField4KeyTyped

    private void txtField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField5KeyPressed

    private void txtField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField5KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField5KeyTyped

    private void txtField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField6KeyPressed

    private void txtField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField6KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField6KeyTyped

    private void txtField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField7KeyPressed

    private void txtField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField7KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField7KeyTyped

    private void txtField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField8KeyPressed

    private void txtField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField8KeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtField8KeyTyped

    private void cmbo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo0ActionPerformed

        JComboBox cmbo = (JComboBox) (evt.getSource());

        if (cmbo.getSelectedIndex() != -1) {

            int hours = Integer.parseInt(cmbo.getSelectedItem() + "");

        }
    }//GEN-LAST:event_cmbo0ActionPerformed

    private void cmbo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo1ActionPerformed

    private void cmbo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo2ActionPerformed

    private void cmbo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo3ActionPerformed

    private void cmbo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo4ActionPerformed

    private void cmbo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo5ActionPerformed

    private void cmbo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo6ActionPerformed

    private void cmbo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbo7ActionPerformed

    private void txtFieldPreviousGPAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldPreviousGPAKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPreviousGPAKeyPressed

    private void txtFieldPreviousGPAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldPreviousGPAKeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && c != '.' && !Character.isDigit(c)) {

            evt.consume();
        }


    }//GEN-LAST:event_txtFieldPreviousGPAKeyTyped

    private void txtFieldFinishedHoursKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldFinishedHoursKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFinishedHoursKeyPressed

    private void txtFieldFinishedHoursKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldFinishedHoursKeyTyped
        JTextField txtField = (JTextField) evt.getSource();

        char c = evt.getKeyChar();

        if (c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE && !Character.isDigit(c)) {

            evt.consume();
        }

        if (txtField.getText().length() > 2) {
            int mark = Integer.parseInt(txtField.getText());

            if (mark > 100) {
                txtField.setText("");
            }
        }
    }//GEN-LAST:event_txtFieldFinishedHoursKeyTyped

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        ArrayList<Integer> marksList = new ArrayList<>();

        int numOfHrs = 0;

        String str = txtField0.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo0.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField1.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo1.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField2.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo2.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField3.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo3.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField4.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo4.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField5.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo5.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField7.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo6.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        str = txtField8.getText();
        if (str.length() > 0) {
            int mark = Integer.parseInt(str);
            int hrs = Integer.parseInt(cmbo7.getSelectedItem() + "");
            numOfHrs += hrs;
            int weightedMark = mark * hrs;
            marksList.add(weightedMark);
        }

        System.out.println(marksList);
        double currGPA = 0;
        int currtotal = 0;

        for (int i = 0; i < marksList.size(); i++) {
            currtotal += marksList.get(i);
        }

        if (numOfHrs != 0) {
            currGPA = ((double) currtotal) / numOfHrs;
        }

        String res = df.format(currGPA);

        currGPA = Double.parseDouble(res);

        System.out.println(currGPA);
        System.out.println(numOfHrs);

        //============================================================
        String prevGPA = txtFieldPreviousGPA.getText();
        String prevHrs = txtFieldFinishedHours.getText();

        if (prevGPA.length() > 0 && prevHrs.length() > 0) {

            double d = Double.parseDouble(prevGPA) * Double.parseDouble(prevHrs);

            d += (currGPA * numOfHrs);

            d = d / (numOfHrs + Double.parseDouble(prevHrs));

            System.out.println(d);

            String s = df.format(d);

            d = Double.parseDouble(s);

            lblShowGPA.setText("GPA = %" + d);
            lblShowHrs.setText("Total Hrs. = "+(int)(numOfHrs + Double.parseDouble(prevHrs)));

        }


    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPA_Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPA_Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPA_Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPA_Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPA_Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JComboBox<String> cmbo0;
    private javax.swing.JComboBox<String> cmbo1;
    private javax.swing.JComboBox<String> cmbo2;
    private javax.swing.JComboBox<String> cmbo3;
    private javax.swing.JComboBox<String> cmbo4;
    private javax.swing.JComboBox<String> cmbo5;
    private javax.swing.JComboBox<String> cmbo6;
    private javax.swing.JComboBox<String> cmbo7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblShowGPA;
    private javax.swing.JLabel lblShowHrs;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextField txtField0;
    private javax.swing.JTextField txtField1;
    private javax.swing.JTextField txtField2;
    private javax.swing.JTextField txtField3;
    private javax.swing.JTextField txtField4;
    private javax.swing.JTextField txtField5;
    private javax.swing.JTextField txtField6;
    private javax.swing.JTextField txtField7;
    private javax.swing.JTextField txtField8;
    private javax.swing.JTextField txtFieldFinishedHours;
    private javax.swing.JTextField txtFieldPreviousGPA;
    // End of variables declaration//GEN-END:variables
}
